alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: redirect.touchtechnology.app
  type: PRIMARY
  zone: touchtechnology.app
- domain: touchcup.asia
  type: ALIAS
  zone: touchcup.asia
- domain: toucheuros.com
  type: ALIAS
  zone: toucheuros.com
name: redirect
region: syd
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: goodtune/redirect
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: redirect
  routes:
  - path: /
  source_dir: /
